package com.careerfocus.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "achievers")
public class Achievers {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "achiever_id", columnDefinition = "INT")
    private int achieverId;

    @Basic
    @Column(nullable = false, length = 1000)
    private String name;

    @Basic
    private String description;
    
    @Basic
    private String contact;

    @Basic
    @Column(name = "is_current")
    private boolean isCurrent;

    @Basic
    @Column(name = "achiever_order", columnDefinition = "INT")
    private int order;

    @Basic
    @Column(name = "img_file_name")
    private String imgFileName;

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY, mappedBy = "achievers", cascade = CascadeType.MERGE)
    private AchieverImage achieverImage;

    public Achievers() {
    }

    public Achievers(int achieverId) {
        this.achieverId = achieverId;
    }

    public int getAchieverId() {
        return achieverId;
    }

    public void setAchieverId(int achieverId) {
        this.achieverId = achieverId;
    }

    public AchieverImage getachieverImage() {
        return achieverImage;
    }

    public void setachieverImage(AchieverImage achieverImage) {
        this.achieverImage = achieverImage;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public boolean isIsCurrent() {
        return isCurrent;
    }

    public void setIsCurrent(boolean isCurrent) {
        this.isCurrent = isCurrent;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public String getImgFileName() {
        return imgFileName;
    }

    public void setImgFileName(String imgFileName) {
        this.imgFileName = imgFileName;
    }

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return String.format("achieverId: %d | name: %s | description: %s | isCurrent: %b | order: %d",
                achieverId, name, description, isCurrent, order);
    }
}