package com.careerfocus.entity;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="announcement_image")
public class AnnouncementImage {
	
	@Id
	@Column(name="announcement_id", columnDefinition="INT")
	private int announcementId;
	
	@Basic
	@Column(columnDefinition="BLOB", nullable=false)
	private byte[] image;
	
	@JsonIgnore
	@OneToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="announcement_id", columnDefinition="INT")
	private Announcements announcements;

	public AnnouncementImage() {
	}

	public AnnouncementImage(int announcementId) {
		this.announcementId = announcementId;
	}
	
	public AnnouncementImage(int announcementId, byte[] image) {
		this.announcementId = announcementId;
		this.image = image;
	}

	public int getAccouncementId() {
		return announcementId;
	}

	public void setAccouncementId(int announcementId) {
		this.announcementId = announcementId;
	}

	public byte[] getImage() {
		return image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}
	
	public Announcements getAnnouncements() {
		return announcements;
	}

	public void setAnnouncements(Announcements announcements) {
		this.announcements = announcements;
	}
}