package com.careerfocus.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="bundle_category")
public class BundleCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="bundle_category_id", columnDefinition="INT")
    private int bundleCategoryId;

    @Basic
    private String name;


    public BundleCategory() {
    }

    public BundleCategory(int bundleCategoryId) {
        this.bundleCategoryId = bundleCategoryId;
    }

    public int getBundleCategoryId() {
        return bundleCategoryId;
    }

    public void setBundleCategoryId(int bundleCategoryId) {
        this.bundleCategoryId = bundleCategoryId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}