package com.careerfocus.entity;

import com.careerfocus.entity.id.BundleQuestionPaperId;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
//@Entity
//@Table(name="bundle_question_paper")
//@IdClass(BundleQuestionPaperId.class)
//public class BundleQuestionPaper {
//    @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
//    @JoinColumn(name="bundle_id", columnDefinition="INT")
//    private Bundle bundle;
//
//    @Id
//    @Column(name="bundle_id", columnDefinition="INT")
//    private int bundleId;
//
//    @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
//    @JoinColumn(name="question_paper_id", columnDefinition="INT")
//    private QuestionPaper questionPaper;
//
//    @Id
//    @Column(name="question_paper_id", columnDefinition="INT")
//    private int questionPaperId;
//
//
//    public BundleQuestionPaper() {
//    }
//
//    public BundleQuestionPaper(int bundleId, int questionPaperId) {
//        this.bundleId = bundleId;
//        this.questionPaperId = questionPaperId;
//    }
//
//    public Bundle getBundle() {
//        return bundle;
//    }
//
//    public void setBundle(Bundle bundle) {
//        this.bundle = bundle;
//    }
//
//    public int getBundleId() {
//        return bundleId;
//    }
//
//    public void setBundleId(int bundleId) {
//        this.bundleId = bundleId;
//    }
//
//    public QuestionPaper getQuestionPaper() {
//        return questionPaper;
//    }
//
//    public void setQuestionPaper(QuestionPaper questionPaper) {
//        this.questionPaper = questionPaper;
//    }
//
//    public int getQuestionPaperId() {
//        return questionPaperId;
//    }
//
//    public void setQuestionPaperId(int questionPaperId) {
//        this.questionPaperId = questionPaperId;
//    }
//}