package com.careerfocus.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "coaching_type_category_sub_image")
public class CoachingTypeCategorySubImage {

    @Id
    @Column(name = "coaching_type_category_sub_id", columnDefinition = "INT")
    private int coachingTypeCategorySubId;

    @Basic
    @Column(columnDefinition = "BLOB", nullable = false)
    private byte[] image;

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "coaching_type_category_sub_id", columnDefinition = "INT")
    private CoachingTypeCategorySub coachingTypeCategorySub;

    public CoachingTypeCategorySubImage() {
    }

    public CoachingTypeCategorySubImage(int coachingTypeCategorySubId) {
        this.coachingTypeCategorySubId = coachingTypeCategorySubId;
    }

    public CoachingTypeCategorySubImage(int coachingTypeCategorySubId, byte[] image) {
        this.coachingTypeCategorySubId = coachingTypeCategorySubId;
        this.image = image;
    }

}