package com.careerfocus.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "coaching_type_category")
public class CoachingTypeCategory {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "coaching_type_category_id", columnDefinition = "INT")
	private int coachingTypeCategoryId;

	@Basic
	@Column(nullable = false, length = 1000)
	private String name;

	@Basic
	@Column(name = "coaching_type_id")
	private int coachingTypeId;
	
	@Basic
	@Column(name = "is_delete")
	private int isDelete;

	@Basic
	@Column(name = "img_file_name")
	private String imgFileName;

	@OneToMany(targetEntity = CoachingTypeCategoryImage.class, mappedBy = "coachingTypeCategory", cascade = CascadeType.ALL)
	private Set<CoachingTypeCategoryImage> coachingTypeCategoryImage = new HashSet<CoachingTypeCategoryImage>();
	
	@OneToMany
    @JoinColumn(name = "coaching_type_category_id")
    @OrderBy("coaching_type_category_id")
    private Set<CoachingTypeCategorySub> coachingTypeCategorySubs = new HashSet<CoachingTypeCategorySub>();

	public CoachingTypeCategory() {
	}

	public CoachingTypeCategory(int coachingTypeCategoryId) {
		this.coachingTypeCategoryId = coachingTypeCategoryId;
	}

	public int getCoachingTypeCategoryId() {
		return coachingTypeCategoryId;
	}

	public void setCoachingTypeCategoryId(int coachingTypeCategoryId) {
		this.coachingTypeCategoryId = coachingTypeCategoryId;
	}

	public int getCoachingTypeId() {
		return coachingTypeId;
	}

	public void setCoachingTypeId(int coachingTypeId) {
		this.coachingTypeId = coachingTypeId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int isDelete() {
		return isDelete;
	}

	public void setDelete(int isDelete) {
		this.isDelete = isDelete;
	}

	public String getImgFileName() {
		return imgFileName;
	}

	public void setImgFileName(String imgFileName) {
		this.imgFileName = imgFileName;
	}

	public Set<CoachingTypeCategoryImage> getCoachingTypeCategoryImage() {
		return coachingTypeCategoryImage;
	}

	public void setCoachingTypeCategoryImage(Set<CoachingTypeCategoryImage> coachingTypeCategoryImage) {
		this.coachingTypeCategoryImage = coachingTypeCategoryImage;
	}
	
	public Set<CoachingTypeCategorySub> getCoachingTypeCategorySubs() {
        return coachingTypeCategorySubs;
	}

	public void setCoachingTypeCategorySubs(Set<CoachingTypeCategorySub> coachingTypeCategorySubs) {
        this.coachingTypeCategorySubs = coachingTypeCategorySubs;
	}

	@Override
	public String toString() {
		return String.format("coachingTypeCategoryId: %d | name: %s | isDelete: %d", coachingTypeCategoryId, name,
				isDelete);
	}
}