package com.careerfocus.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="question_paper_sub_category")
public class QuestionPaperSubCategory {
	@Basic
	@Column(length=2000)
	private String description;

	@Basic
	@Column(length=200)
	private String name;

	@Basic
	@Column(name="no_of_questions", columnDefinition="INT")
	private int noOfQuestions;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="question_paper_category_id", columnDefinition="INT", nullable=false)
	private QuestionPaperCategory questionPaperCategory;

	@Id
	@Column(name="question_paper_sub_category_id", columnDefinition="INT")
	private int questionPaperSubCategoryId;


	public QuestionPaperSubCategory() {
	}

	public QuestionPaperSubCategory(int questionPaperSubCategoryId) {
		this.questionPaperSubCategoryId = questionPaperSubCategoryId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNoOfQuestions() {
		return noOfQuestions;
	}

	public void setNoOfQuestions(int noOfQuestions) {
		this.noOfQuestions = noOfQuestions;
	}

	public QuestionPaperCategory getQuestionPaperCategory() {
		return questionPaperCategory;
	}

	public void setQuestionPaperCategory(QuestionPaperCategory questionPaperCategory) {
		this.questionPaperCategory = questionPaperCategory;
	}

	public int getQuestionPaperSubCategoryId() {
		return questionPaperSubCategoryId;
	}

	public void setQuestionPaperSubCategoryId(int questionPaperSubCategoryId) {
		this.questionPaperSubCategoryId = questionPaperSubCategoryId;
	}
}