package com.careerfocus.entity;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="question_paper")
public class QuestionPaper {
	
	@Basic
	@Column(name="correct_answer_mark", columnDefinition="FLOAT")
	private float correctAnswerMark;

	@Basic
	@Column(name="course_name", nullable=false)
	private String courseName;

	@Basic
	@Column(columnDefinition="INT")
	private int duration;

	@Basic
	@Column(name="exam_code", nullable=false, length=45)
	private String examCode;

	@Basic
	@Column(name="is_demo")
	private boolean isDemo;

	@Basic
	@Column(nullable=false, length=150)
	private String name;

	@Basic
	@Column(name="negative_mark", columnDefinition="FLOAT")
	private float negativeMark;

	@Basic
	@Column(name="no_of_options", columnDefinition="INT")
	private int noOfOptions;

	@Basic
	@Column(name="no_of_questions", columnDefinition="INT")
	private int noOfQuestions;

	@OneToMany(targetEntity=QuestionPaperCategory.class, mappedBy="questionPaper", cascade=CascadeType.MERGE)
	private Set<QuestionPaperCategory> questionPaperCategorys = new HashSet<QuestionPaperCategory>();

	@Id
	@Column(name="question_paper_id", columnDefinition="INT")
	private int questionPaperId;


	public QuestionPaper() {
	}

	public QuestionPaper(int questionPaperId) {
		this.questionPaperId = questionPaperId;
	}

	public float getCorrectAnswerMark() {
		return correctAnswerMark;
	}

	public void setCorrectAnswerMark(float correctAnswerMark) {
		this.correctAnswerMark = correctAnswerMark;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public String getExamCode() {
		return examCode;
	}

	public void setExamCode(String examCode) {
		this.examCode = examCode;
	}

	public boolean isIsDemo() {
		return isDemo;
	}

	public void setIsDemo(boolean isDemo) {
		this.isDemo = isDemo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getNegativeMark() {
		return negativeMark;
	}

	public void setNegativeMark(float negativeMark) {
		this.negativeMark = negativeMark;
	}

	public int getNoOfOptions() {
		return noOfOptions;
	}

	public void setNoOfOptions(int noOfOptions) {
		this.noOfOptions = noOfOptions;
	}

	public int getNoOfQuestions() {
		return noOfQuestions;
	}

	public void setNoOfQuestions(int noOfQuestions) {
		this.noOfQuestions = noOfQuestions;
	}

	public Set<QuestionPaperCategory> getQuestionPaperCategorys() {
		return questionPaperCategorys;
	}

	public void setQuestionPaperCategorys(Set<QuestionPaperCategory> questionPaperCategorys) {
		this.questionPaperCategorys = questionPaperCategorys;
	}

	public int getQuestionPaperId() {
		return questionPaperId;
	}

	public void setQuestionPaperId(int questionPaperId) {
		this.questionPaperId = questionPaperId;
	}
}