package com.careerfocus.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "slider_image")
public class SliderImage {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "slider_image_id", columnDefinition = "INT")
    private int sliderImageId;
    
    @Basic
    @Column(name = "is_current")
    private int isCurrent;

    @Basic
    @Column(columnDefinition = "BLOB", nullable = false)
    private byte[] image;

    public SliderImage() {
    }

    public SliderImage(byte[] image) {
        this.image = image;
    }

    public SliderImage(int sliderImageId, byte[] image) {
        this.sliderImageId = sliderImageId;
        this.image = image;
    }

    public int getSliderImageId() {
        return sliderImageId;
    }

    public void setSliderImageId(int sliderImageId) {
        this.sliderImageId = sliderImageId;
    }
    
    public int isIsCurrent() {
        return isCurrent;
    }

    public void setIsCurrent(int isCurrent) {
        this.isCurrent = isCurrent;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

}