package com.careerfocus.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "slider_image")
public class SliderImage {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "slider_id", columnDefinition = "INT")
    private int sliderId;

    @Basic
    @Column(columnDefinition = "BLOB", nullable = false)
    private byte[] image;

    public SliderImage() {
    }

    public SliderImage(byte[] image) {
        this.image = image;
    }

    public SliderImage(int sliderId, byte[] image) {
        this.sliderId = sliderId;
        this.image = image;
    }

    public int getsliderId() {
        return sliderId;
    }

    public void setsliderId(int sliderId) {
        this.sliderId = sliderId;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

}