package com.careerfocus.entity;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "slider_announcement")
public class SliderAnnouncement {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "slider_announcement_id", columnDefinition = "INT")
    private int sliderAnnouncementId;
    
    @Basic
    @Column(name = "is_current")
    private boolean isCurrent;

    @Basic
    private String announcement;

    public SliderAnnouncement() {
    }

    public SliderAnnouncement(String announcement) {
        this.announcement = announcement;
    }

    public SliderAnnouncement(int sliderAnnouncementId, String announcement) {
        this.sliderAnnouncementId = sliderAnnouncementId;
        this.announcement = announcement;
    }

    public int getSliderAnnouncementId() {
        return sliderAnnouncementId;
    }

    public void setSliderAnnouncementId(int sliderAnnouncementId) {
        this.sliderAnnouncementId = sliderAnnouncementId;
    }
    
    public boolean isIsCurrent() {
        return isCurrent;
    }

    public void setIsCurrent(boolean isCurrent) {
        this.isCurrent = isCurrent;
    }

    public String getAnnouncement() {
        return announcement;
    }

    public void setAnnouncement(String announcement) {
        this.announcement = announcement;
    }

}