package com.careerfocus.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "testimonial_image")
public class TestimonialImage {

    @Id
    @Column(name = "testimonial_id", columnDefinition = "INT")
    private int testimonialId;

    @Basic
    @Column(columnDefinition = "BLOB", nullable = false)
    private byte[] image;

    @JsonIgnore
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "testimonial_id", columnDefinition = "INT")
    private Testimonial testimonial;
    

    public TestimonialImage() {
    }

    public TestimonialImage(int testimonialId) {
        this.testimonialId = testimonialId;
    }

    public TestimonialImage(int testimonialId, byte[] image) {
        this.testimonialId = testimonialId;
        this.image = image;
    }

    public int gettestimonialId() {
        return testimonialId;
    }

    public void settestimonialId(int testimonialId) {
        this.testimonialId = testimonialId;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public Testimonial getTestimonial() {
        return testimonial;
    }

    public void setTestimonial(Testimonial testimonial) {
        this.testimonial = testimonial;
    }
}