package com.careerfocus.entity;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="testimonials")
public class Testimonial implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7771123685493038212L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="testimonial_id", columnDefinition="INT")
	private int testimonialId;
	
	@Basic
	@Column(nullable=false, length=45)
	private String content;

	@Basic
	@Column(nullable=false)
	@Temporal(TemporalType.DATE)
	private Date date;


	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="user_id", columnDefinition="INT", nullable=false)
	private User user;


	public Testimonial() {
	}

	public Testimonial(int testimonialId) {
		this.testimonialId = testimonialId;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getTestimonialId() {
		return testimonialId;
	}

	public void setTestimonialId(int testimonialId) {
		this.testimonialId = testimonialId;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}