package com.careerfocus.entity;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="user")

public class User {
	
	
	@Basic
	@Column(name="center_id", nullable=false, length=12)
	private String centerId;

	@Basic
	@Column(name="created_date", nullable=false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdDate;

	@Basic
	@Temporal(TemporalType.DATE)
	private Date dob;

	@Basic
	@Column(name="fee_status", nullable=false, length=45)
	private String feeStatus;

	@Basic
	@Column(name="first_name", nullable=false, length=46)
	private String firstName;

	@Basic
	@Column(length=11)
	private String gender;

	@Basic
	@Column(name="last_name", nullable=false, length=46)
	private String lastName;

	@Basic
	@Column(nullable=false, length=45)
	private String password;

	@Basic
	@Column(columnDefinition="INT")
	private int role;

	@Basic
	@Column(columnDefinition="INT")
	private int status;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="user_id", columnDefinition="INT")
	private int userId;

	@Basic
	@Column(nullable=false, length=45)
	private String username;


	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public String getCenterId() {
		return centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getFeeStatus() {
		return feeStatus;
	}

	public void setFeeStatus(String feeStatus) {
		this.feeStatus = feeStatus;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRole() {
		return role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}